### ISSUE TITLE
Failed to run with GitHub Actions, Mac, Linux when using new logging method

### ISSUE THREAD

**Issue by gorouflex** [MrLoLf/HoneygainAutoClaim#14]
```
Traceback (most recent call last):
  File "/home/runner/work/HoneygainAutoClaim/HoneygainAutoClaim/main.py", line 18, in <module>
    from colorama import just_fix_windows_console, Fore
ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/usr/lib/python3/dist-packages/colorama/__init__.py)
Error: Process completed with exit code 1.
```

idk if i can change from Linux to Windows

**Comment by gorouflex** [comment]
```
Started HoneygainAutoClaim!
Your repo is not up-to-date with the original repo
Please update your repo to the latest commit to get new updates and bug fixes
Creating config folder!
Generating new Config.
Traceback (most recent call last):
  File "D:\a\HoneygainAutoClaim\HoneygainAutoClaim\main.py", line 253, in <module>
    def gen_token(s: requests.session, invalid: bool = False) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Error: Process completed with exit code 1.
```

i changed to Windows but i don’t know how Mac and Linux users can use this thing anymore?

@MrLoLf

**Comment by MrLoLf** [comment]
Should now be fixed, thanks for the report.
