### ISSUE TITLE
[BUG] New Honeygain API changes

### ISSUE THREAD

**Issue by gorouflex** [MrLoLf/HoneygainAutoClaim#33]
```
➜  Downloads cd '/Users/gorouflex/Downloads/' && '/usr/local/bin/python3'  '/Users/gorouflex/Downloads/main-2.py'  && echo Exit status: $? && exit 1
Started HoneygainAutoClaim!
Traceback (most recent call last):
  File "/Users/gorouflex/Downloads/main-2.py", line 483, in <module>
    main()
  File "/Users/gorouflex/Downloads/main-2.py", line 473, in main
    pot_claim(s, header)
  File "/Users/gorouflex/Downloads/main-2.py", line 435, in pot_claim
    logging.info(f'%sClaimed {pot_claimed["data"]["credits"]} Credits.', WHITE)
                              ~~~~~~~~~~~^^^^^^^^
KeyError: 'data'
```

**Comment by gorouflex** [comment]
Affected [commit](https://github.com/MrLoLf/HoneygainAutoClaim/commit/115d28f5e96da07e84bb899da82f2568845b18b3)

**Comment by gorouflex** [comment]
yeah they just `Rebranded` today

**Comment by gorouflex** [comment]
For more [information](https://www.honeygain.com/blog/a-new-chapter-for-honeygain-the-bees-have-rebranded/?utm_source=social_media&utm_medium=notification&utm_campaign=blogpost&utm_content=new_bb)

**Comment by gorouflex** [comment]
they changed `credits` to `winning_credits`
This is my dump file:
```
Current API URLs:
 - Login: https://dashboard.honeygain.com/api/v1/users/tokens
 - Lucky Pot: https://dashboard.honeygain.com/api/v1/contest_winnings
 - Balance: https://dashboard.honeygain.com/api/v1/users/balances
 - Achievements: https://dashboard.honeygain.com/api/v1/achievements/
 - Achievement Claim: https://dashboard.honeygain.com/api/v1/achievements/claim
Pot Winnings:
{'meta': None, 'data': {'progress_bytes': 15000000, 'max_bytes': 15000000, 'winning_credits': 2.0}}
Current Balance:
{'meta': None, 'data': {'realtime': {'credits': 12.43, 'usd_cents': 1}, 'payout': {'credits': 18705.23, 'usd_cents': 1871}, 'min_payout': {'credits': 20000.0, 'usd_cents': 2000}}}
```

**Comment by gorouflex** [comment]
Completely dumped from Honeygain API V1:
```
Pot Winnings:
{
  "meta": null,
  "data": {
    "progress_bytes": 15000000,
    "max_bytes": 15000000,
    "winning_credits": 2.0
  }
}
Current Balance:
{
  "meta": null,
  "data": {
    "realtime": {
      "credits": 12.57,
      "usd_cents": 1
    },
    "payout": {
      "credits": 18705.38,
      "usd_cents": 1871
    },
    "min_payout": {
      "credits": 20000.0,
      "usd_cents": 2000
    }
  }
}
Achievements:
{
  "meta": {
    "pagination": null,
    "ordering": null
  },
  "data": [
    {
      "id": "5a92c139-41cb-11ee-af5f-f02f7497e25b",
      "title": "JumpTask Starter",
      "description": "Complete 1 task on <a href=\"https://app.jumptask.io/offers\" target=\"_blank\" rel=\"noreferrer\">JumpTask</a> Offers section, receive the reward on your linked JumpTask account & gain this achievement!",
      "image_slug": "jumptask_starter",
      "is_locked": false,
      "is_claimed": false,
      "claimed_at": null,
      "progresses": [
        {
          "current_progress": 0,
          "total_progress": 1,
          "progress_type": "jt_task_completed"
        }
      ],
      "rewards": [
        {
          "name": "jt_starter",
          "type": "sticker",
          "amount": 1
        }
      ],
      "slug": "jumptask_starter"
    },
    {
      "id": "5a93402f-41cb-11ee-98f5-f02f74979a4c",
      "title": "JumpTask Gainer",
      "description": "Complete 3 tasks on <a href=\"https://app.jumptask.io/offers\" target=\"_blank\" rel=\"noreferrer\">JumpTask</a> Offers section, receive the rewards on your linked JumpTask account & gain this achievement!",
      "image_slug": "jumptask_gainer",
      "is_locked": false,
      "is_claimed": false,
      "claimed_at": null,
      "progresses": [
        {
          "current_progress": 0,
          "total_progress": 3,
          "progress_type": "jt_task_completed"
        }
      ],
      "rewards": [
        {
          "name": "jt_gainer",
          "type": "sticker",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 20
        }
      ],
      "slug": "jumptask_gainer"
    },
    {
      "id": "5a93fb39-41cb-11ee-b373-f02f749621c6",
      "title": "JumpTask Pro",
      "description": "Complete 5 tasks on <a href=\"https://app.jumptask.io/offers\" target=\"_blank\" rel=\"noreferrer\">JumpTask</a> Offers section, receive the rewards on your linked JumpTask account & gain this achievement!",
      "image_slug": "jumptask_pro",
      "is_locked": false,
      "is_claimed": false,
      "claimed_at": null,
      "progresses": [
        {
          "current_progress": 0,
          "total_progress": 5,
          "progress_type": "jt_task_completed"
        }
      ],
      "rewards": [
        {
          "name": "jt_pro",
          "type": "sticker",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 50
        }
      ],
      "slug": "jumptask_pro"
    },
    {
      "id": "34538ae3-cb7b-11ed-9051-f02f74979a4c",
      "title": "Honeygain Buddy",
      "description": "Invite 1 new friend to join Honeygain. They need to register and add at least one device! Find your referral link in the <a href=\"https://dashboard.honeygain.com/referrals\" target=\"_blank\" rel=\"noreferrer\">referrals page</a>.",
      "image_slug": "buddy",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-12-14 14:07:16",
      "progresses": [
        {
          "current_progress": 1,
          "total_progress": 1,
          "progress_type": "referral_first_device"
        }
      ],
      "rewards": [
        {
          "name": "high_five",
          "type": "sticker",
          "amount": 1
        }
      ],
      "slug": "buddy"
    },
    {
      "id": "345493cc-cb7b-11ed-89e4-f02f7497e25b",
      "title": "Bronze Pot",
      "description": "Open the Lucky Pot 7 times in a row. Don\u2019t miss any days to complete!",
      "image_slug": "bronze_pot",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-10-09 23:12:02",
      "progresses": [
        {
          "current_progress": 7,
          "total_progress": 7,
          "progress_type": "lucky_pot_consecutive_opens"
        }
      ],
      "rewards": [
        {
          "name": "7_pot",
          "type": "streak",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 50
        }
      ],
      "slug": "bronze_pot"
    },
    {
      "id": "34557383-cb7b-11ed-8b83-f02f749621c6",
      "title": "Silver Pot",
      "description": "Open the Lucky Pot 14 times in a row. Don\u2019t miss any days to complete!",
      "image_slug": "silver_pot",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-11-18 14:05:56",
      "progresses": [
        {
          "current_progress": 14,
          "total_progress": 14,
          "progress_type": "lucky_pot_consecutive_opens"
        }
      ],
      "rewards": [
        {
          "name": "14_pot",
          "type": "streak",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 100
        }
      ],
      "slug": "silver_pot"
    },
    {
      "id": "34564036-cb7b-11ed-8b83-f02f749621c6",
      "title": "Gold Pot",
      "description": "Open the Lucky Pot 21 times in a row. Don\u2019t miss any days to complete!",
      "image_slug": "gold_pot",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-12-09 02:31:09",
      "progresses": [
        {
          "current_progress": 21,
          "total_progress": 21,
          "progress_type": "lucky_pot_consecutive_opens"
        }
      ],
      "rewards": [
        {
          "name": "21_pot",
          "type": "streak",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 150
        }
      ],
      "slug": "gold_pot"
    },
    {
      "id": "34570695-cb7b-11ed-89e4-f02f7497e25b",
      "title": "Diamond Pot",
      "description": "Open the Lucky Pot 30 times in a row. Don\u2019t miss any days to complete!",
      "image_slug": "diamond_pot",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2024-01-09 14:08:09",
      "progresses": [
        {
          "current_progress": 30,
          "total_progress": 30,
          "progress_type": "lucky_pot_consecutive_opens"
        }
      ],
      "rewards": [
        {
          "name": "30_pot",
          "type": "streak",
          "amount": 1
        },
        {
          "name": null,
          "type": "credits",
          "amount": 300
        }
      ],
      "slug": "diamond_pot"
    },
    {
      "id": "5a91e8e0-41cb-11ee-98f5-f02f74979a4c",
      "title": "Become a JumpTasker",
      "description": "Discover and switch to JumpTask mode! Toggle the switch button, add your <a href=\"https://app.jumptask.io/my-account\" target=\"_blank\" rel=\"noreferrer\">JumpTask</a> account ID to Honeygain\u2019s profile and enjoy your passive earnings & achievement!",
      "image_slug": "jumptasker",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-09-05 13:08:11",
      "progresses": [
        {
          "current_progress": 1,
          "total_progress": 1,
          "progress_type": "jt_wallet_added"
        }
      ],
      "rewards": [
        {
          "name": "jumptasker",
          "type": "sticker",
          "amount": 1
        }
      ],
      "slug": "jumptasker"
    },
    {
      "id": "3452cfe0-cb7b-11ed-89e4-f02f7497e25b",
      "title": "Onboarding Tasks",
      "description": "Complete tasks to unlock achievements! Welcome to the hive -- you are a true Honeygainer now!",
      "image_slug": "onboarding",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-03-26 02:09:17",
      "progresses": [],
      "rewards": [
        {
          "name": "rookie",
          "type": "sticker",
          "amount": 1
        }
      ],
      "slug": "onboarding"
    },
    {
      "id": "71eb2f81-e446-11ed-bef8-f02f7497e25b",
      "title": "Steady Gainer",
      "description": "Have 1 or more active desktop devices and gather at least 1GB of traffic. Want to add desktop devices? Download our app today.",
      "image_slug": "steady_gainer",
      "is_locked": false,
      "is_claimed": true,
      "claimed_at": "2023-05-01 14:57:31",
      "progresses": [],
      "rewards": [
        {
          "name": "busy_bee",
          "type": "sticker",
          "amount": 1
        }
      ],
      "slug": "steady_gainer_add_active"
    }
  ]
}
```

**Comment by gorouflex** [comment]
@MrLoLf Should we change this
```
logging.info(f'%sClaimed {pot_claimed["data"]["credits"]} Credits.', WHITE)
```
to this?
```
logging.info(f'%sClaimed {pot_claimed["data"]["winning_credits"]} Credits.', WHITE)
```

Since there is no `credits` in the Pot Winning ( maybe I'm wrong )

**Comment by MrLoLf** [comment]
This might fix the issue, but if they have changed more it may not be the only change required. I'll have time to look into this at the end of my day, as I'm currently working.

**Comment by gorouflex** [comment]
Maybe, I will test tomorrow 😮

**Comment by gorouflex** [comment]
![image](https://github.com/MrLoLf/HoneygainAutoClaim/assets/98001973/9f71275c-4795-441a-9ddc-ff2d2a2505e6)
@MrLoLf Closed
